### ISSUE TITLE
Cascading Flow Exception

### ISSUE THREAD

**Issue by Nevil-DSOUZA** [jpmml/jpmml-cascading#2]
When I run this Program at First time  with PMML file 'iris.nn.xml' and 'iris.nn.tsv' file It execute Successfully.But Second Time Execute with same PMML file and  tsv file It give the Exception as "field name already exists: species" .
Exception in thread "main" cascading.flow.planner.PlannerException: could not build flow from assembly: [field name already exists: species]
    at cascading.flow.planner.FlowPlanner.handleExceptionDuringPlanning(FlowPlanner.java:578)
    at cascading.flow.hadoop.planner.HadoopPlanner.buildFlow(HadoopPlanner.java:286)
    at cascading.flow.hadoop.planner.HadoopPlanner.buildFlow(HadoopPlanner.java:80)
    at cascading.flow.FlowConnector.connect(FlowConnector.java:459)
    at org.jpmml.cascading.Main.main(Main.java:93)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:156)
Caused by: cascading.tuple.TupleException: field name already exists: species
    at cascading.tuple.Fields.copyRetain(Fields.java:1397)
    at cascading.tuple.Fields.appendInternal(Fields.java:1266)
    at cascading.tuple.Fields.append(Fields.java:1215)
    at org.jpmml.cascading.PMMLPlanner.resolveAssembly(PMMLPlanner.java:136)
    at org.jpmml.cascading.PMMLPlanner.resolveTails(PMMLPlanner.java:96)
    at cascading.flow.planner.FlowPlanner.resolveAssemblyPlanners(FlowPlanner.java:153)
    at cascading.flow.planner.FlowPlanner.resolveTails(FlowPlanner.java:140)
    at cascading.flow.hadoop.planner.HadoopPlanner.buildFlow(HadoopPlanner.java:246)

**Comment by vruusmann** [comment]
The example application is stateless. Therefore, this behaviour must be linked to your execution environment.

Did you delete the output directory of the first run before launching the second run? Does the error persist if you redirect the output of the second run to some other directory?

**Comment by Nevil-DSOUZA** [comment]
just now i tried deleting the Output files and executed it and even change the output path. Still issue persists 
I am running this locally.

**Comment by vruusmann** [comment]
I can see that you are using `iris.nn.xml` and `iris.nn.tsv` files that originate from the samples section of the [Cascading Pattern](https://github.com/Cascading/pattern) project.

You are getting this exception, because the `iris.nn.xml` file is invalid. It contains a duplicate `species` field definition (first as a target field, then as an output field).

**Comment by Nevil-DSOUZA** [comment]
I tried deleting  <OutputField name="species" />  in PMML file and it worked fine.Thanks for your  reply.
