### ISSUE TITLE
Duplicate field name found

### ISSUE THREAD

**Issue by nitinmahesh** [jpmml/jpmml-cascading#4]
Also i tried to execute the jpmml-cascading and i am getting this exception:

Exception in thread "main" cascading.flow.planner.PlannerException: could not build flow from assembly: [duplicate field name found: C]
    at cascading.flow.planner.FlowPlanner.handleExceptionDuringPlanning(FlowPlanner.java:590)
    at cascading.flow.hadoop.planner.HadoopPlanner.buildFlow(HadoopPlanner.java:293)
    at cascading.flow.hadoop.planner.HadoopPlanner.buildFlow(HadoopPlanner.java:80)
    at cascading.flow.FlowConnector.connect(FlowConnector.java:459)
    at org.jpmml.cascading.Main.main(Main.java:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
Caused by: java.lang.IllegalArgumentException: duplicate field name found: C
    at cascading.tuple.Fields.validate(Fields.java:835)
    at cascading.tuple.Fields.<init>(Fields.java:632)
    at cascading.scheme.util.DelimitedParser.parseFirstLine(DelimitedParser.java:312)
    at cascading.scheme.hadoop.TextDelimited.retrieveSourceFields(TextDelimited.java:975)
    at cascading.tap.Tap.retrieveSourceFields(Tap.java:366)
    at cascading.flow.BaseFlow.retrieveSourceFields(BaseFlow.java:230)
    at cascading.flow.BaseFlow.<init>(BaseFlow.java:196)
    at cascading.flow.hadoop.HadoopFlow.<init>(HadoopFlow.java:98)
    at cascading.flow.hadoop.planner.HadoopPlanner.createFlow(HadoopPlanner.java:238)
    at cascading.flow.hadoop.planner.HadoopPlanner.buildFlow(HadoopPlanner.java:251)
    ... 8 more

My input file is having this first record:
y,unique_id,wgt,r_busb,prob_b,prob_rnk1,prob_rnk2,prob_rnk3,new_comm_bur_cnt_4,comm_inq_sum,comm_hit,unique_domain,pct_company,n_open,r_open_mer_pg_vis,act_sup,C,K,C,N,N,N,N,N,C,C,C,C,C,L,N,C

and then after all the input data records for scoring. Can you please check why the duplicates are not allowed.

Note: Same i tried to run through JPMML-Evaluator example code and it was through and was able to get the score.

**Comment by vruusmann** [comment]
You have **eight** columns named `C` and **six** columns named `N` in your CSV file. Now, if a PMML model expects `C` and `N` as input, then which two columns out of those fourteen should it choose?

Cascading is doing the right thing when complaining about invalid CSV file - please fix it by deleting unnecessary columns. I will fix the JPMML-Evaluator example application so that it will enforce this "column name must be unique"-constraint more strictly.
