### ISSUE TITLE
Exception in thread "main" cascading.flow.FlowException: step failed: (1/1)

### ISSUE THREAD

**Issue by vmuraliraju** [jpmml/jpmml-cascading#7]
Exception in thread "main" cascading.flow.FlowException: step failed: (1/1) /test/vittabai, with job id: job_1453567420128_0001, please see cluster logs for failure messages
    at cascading.flow.planner.FlowStepJob.blockOnJob(FlowStepJob.java:261)
    at cascading.flow.planner.FlowStepJob.start(FlowStepJob.java:162)
    at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:124)
    at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:43)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Log ...........................................

016-01-24 22:55:59,532 INFO [Thread-80] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerAllocator: History url is http://quickstart.cloudera:19888/jobhistory/job/job_1453185973876_0002
2016-01-24 22:55:59,554 INFO [Thread-80] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerAllocator: Waiting for application to be successfully unregistered.
2016-01-24 22:56:00,556 INFO [Thread-80] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerAllocator: Final Stats: PendingReds:0 ScheduledMaps:0 ScheduledReds:0 AssignedMaps:2 AssignedReds:0 CompletedMaps:0 CompletedReds:0 ContAlloc:12 ContRel:4 HostLocal:2 RackLocal:0
2016-01-24 22:56:00,558 INFO [Thread-80] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: Deleting staging directory hdfs://quickstart.cloudera:8020 /tmp/hadoop-yarn/staging/cloudera/.staging/job_1453185973876_0002
2016-01-24 22:56:00,563 INFO [Thread-80] org.apache.hadoop.ipc.Server: Stopping server on 48947
2016-01-24 22:56:00,567 INFO [IPC Server listener on 48947] org.apache.hadoop.ipc.Server: Stopping IPC Server listener on 48947
2016-01-24 22:56:00,569 INFO [IPC Server Responder] org.apache.hadoop.ipc.Server: Stopping IPC Server Responder
2016-01-24 22:56:00,570 INFO [TaskHeartbeatHandler PingChecker] org.apache.hadoop.mapreduce.v2.app.TaskHeartbeatHandler: TaskHeartbeatHandler thread interrupted

**Comment by vruusmann** [comment]
Please fix your Apache Hadoop configuration. This issue has got absolutely nothing to do with the JPMML-Cascading library.
